# Địa chỉ và port mà node sẽ lắng nghe các kết nối đến từ các peer khác.
# Ví dụ: "/ip4/0.0.0.0/tcp/9001" (lắng nghe trên tất cả các interface IPv4, port 9001, dùng TCP)
# Hoặc "/ip4/0.0.0.0/udp/9001/quic-v1" (dùng QUIC qua UDP)
listenAddress: "/ip4/0.0.0.0/udp/8004/quic-v1"

# Khóa riêng tư của node, được mã hóa bằng Base64.
# Nếu để trống hoặc không có trường này, ManagedNode sẽ tự tạo một khóa mới (hữu ích cho dev/test).
# Để tạo một khóa: bạn có thể dùng các công cụ libp2p hoặc để node tự tạo lần đầu rồi sao chép ra.
privateKey: "CAESQNwKcpNp9Op6g2isGnZ9FnadbDee0zmXbcjxg2sFWYUoVeJQiMFtdCRx/qzsX8lkDZwjuAfWg7QyEU2kLzMrgZg="

# Danh sách các bootstrap peer để node kết nối khi khởi động.
# Mỗi peer là một multiaddress đầy đủ (bao gồm /p2p/<PeerID>).
bootstrapPeers:
  - "/ip4/127.0.0.1/udp/8002/quic-v1/p2p/12D3KooWG5bKDw3hc3fsDd1PY4cR3JDfhDn1abbHRKig5mfeQGqK"
  - "/ip4/127.0.0.1/udp/8003/quic-v1/p2p/12D3KooWEBSxQRsY3akf5gMKZsmiY7zthkV8LSk7PdP4YSXJTiXA"
masterNodeAddress: "/ip4/127.0.0.1/tcp/9000/p2p/12D3KooWM3MudyzXTZTUafyxXQQBNKeK9cpX9QekgB9bPsRwNGvS"
# Loại của node này (ví dụ: "master", "sub", "validator", "light-client").
# Logic ứng dụng của bạn có thể dựa vào giá trị này.
nodeType: "consensus"

# Đường dẫn đến thư mục gốc nơi node có thể lưu trữ dữ liệu (ví dụ: database, logs).
rootPath: "./node_data_4"

# Kích thước buffer cho kênh transaction (nếu ứng dụng của bạn sử dụng).
transactionChanBuffer: 2000

# Cấu hình quản lý kết nối
minConnections: 5        # Số kết nối tối thiểu mà node cố gắng duy trì.
maxConnections: 50       # Số kết nối tối đa được phép.
connectionGracePeriod: "20s" # Thời gian chờ cho các kết nối mới trước khi connection manager có thể đóng chúng nếu vượt quá maxConnections. (ví dụ: "1m30s")
initialReconnectDelay: "5s"  # Độ trễ ban đầu trước khi thử kết nối lại với peer đã mất.
maxReconnectDelay: "1m"      # Độ trễ tối đa giữa các lần thử kết nối lại.
maxReconnectAttempts: 10       # Số lần thử kết nối lại tối đa trước khi từ bỏ (0 hoặc số âm nghĩa là thử vô hạn).
pingInterval: "30s"          # Khoảng thời gian giữa các lần ping để kiểm tra peer còn sống.
pingTimeout: "10s"           # Thời gian chờ tối đa cho một phản hồi ping.

# Cấu hình PubSub
maxMessageSize: 10485760 # Kích thước message tối đa cho PubSub (tính bằng byte, ví dụ: 10MiB).

# Cấu hình Cache (ví dụ: LRU cache cho key-value)
keyValueCacheSize: 2000   # Số lượng mục tối đa trong cache.

# (Tùy chọn) Danh sách các protocol ID mà node này hỗ trợ (ngoài các protocol mặc định của libp2p).
supportedProtocols:
  - "/meta-node/transactions-request/1.0.0" # Protocol cho yêu cầu giao dịch
  - "/meta-node/sync-request/1.0.0"         # Protocol cho yêu cầu đồng bộ hóa (ĐÃ THÊM)

initialStake: 10
allStakers:
  - pubKeyHex: "d3f1e819826fce29566bb38864e16fb218cf7bfd38f326ae5d5194974080d025"
    stake: 10
  - pubKeyHex: "5d0cb2b99c7024c7688285e5eadc67c604b78672c7502dfc7f4794d6dec218b6"
    stake: 10
  - pubKeyHex: "40d55b8f283ca3f1ec99a6729af7dbeefe146ae4a0cab9b28a7e395f812b9139"
    stake: 10
  - pubKeyHex: "55e25088c16d742471feacec5fc9640d9c23b807d683b432114da42f332b8198" # Creator thứ 4 từ log
    stake: 10 # Giả sử node này cũng có stake là 10


consensusTickInterval: "1s"